id: A70079B4F
title: Toh_514-Discourse_of_Dh%C4%81ra%E1%B9%87%C4%AB_of_Buddha%E2%80%99s_Essence-v2
type: translation
pechas:
- IA1C1663A
- IF8AA4956
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-088-008
  eft-text-version: 1.1.10 2021
  title: Toh_514-Discourse_of_Dh%C4%81ra%E1%B9%87%C4%AB_of_Buddha%E2%80%99s_Essence-v2
alignment_to_base:
  IA1C1663A/CBF3: 12B1
  IF8AA4956/A39E: 12B1
